---
title: "Reproducible Research Peer Assessment 1"
author: "Aziah"
date: "February 27, 2016"
output: html_document
---

## Required libraries are:
```{R}
library(knitr)
library(ggplot2)   
library(data.table)
library(lattice)
```

## 1. Loading and preprocessing the data
```{R}
steps_data <- read.csv("activity.csv", header=TRUE, sep =",",
                      colClasses=c("numeric","character","numeric"))
```
### Checking and tidying up the data

```{R}
head(steps_data)
```
```{R}
names(steps_data)
```
Convert the date to **Date class** and interval to **Factor class**

```{R}
steps_data$date <- as.Date(steps_data$date, format = "%Y-%m-%d")  
steps_data$interval <- as.factor(steps_data$interval)
```
Check using str():

```{R}
str(steps_data)
```


## 2. What is mean total number of steps taken per day?
a. Calculating the total number of steps taken per day - ignoring the missing values

```{R}
steps_per_day <- aggregate(steps ~ date, data = steps_data, sum, na.rm = TRUE)
```
b. The histogram would be as follows:

```{R}
hist(steps_per_day$steps, main = "Total Number of Steps per Day", xlab = "Days", col = "blue")
```

c. Mean and median of the total number of steps taken per day

```{R}
mean(steps_per_day$steps)
```
```{R}
median(steps_per_day$steps)
```

## 3. What is the average daily activity pattern?

a. Making a time series plot of the 5-minute interval (x-axis) and the avg number of steps taken, averaged across all days (y-axis).

Getting the average:

```{R}
time_series <- tapply(steps_data$steps, steps_data$interval, mean, na.rm=TRUE)
```
Plotting the result:

```{R}
plot(row.names(time_series), time_series, type = "l", xlab = "5-min Interval", ylab = "Average across all days", main = "Average Daily Activity Pattern", col = "Black")
```

b. Finding the average that contains the max number of steps

```{R}
max_interval <- which.max(time_series)
names(max_interval)
```

## 4. Imputing missing values

a. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

```{R}
steps_data_NA <- sum(is.na(steps_data))
steps_data_NA
```
b. Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

First, NA being replaced with mean in 5-min interval
```{R}
steps_average <- aggregate(steps ~ interval, data = steps_data, FUN = mean)
fill_NA <- numeric()
for (i in 1:nrow(steps_data)) {
    df <- steps_data[i,]
    if (is.na(df$steps)) {
      steps <- subset(steps_average, interval == df$interval)$steps
    } else {
      steps <- df$steps
    }
    fill_NA <- c(fill_NA, steps)
}
```

c. Create a new dataset that is equal to the original dataset but with the missing data filled in.

```{R}
new_steps_data <- steps_data
new_steps_data$steps <- fill_NA
```

d. Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

```{R}
steps_per_day2 <- aggregate(steps ~ date, data = new_steps_data, sum, na.rm=TRUE)
```
The histogram is:

```{R}
hist(steps_per_day2$steps, main = "Total Steps Per Day", xlab = "Days", col = "Green")
```

The mean and the median are:

```{R}
mean(steps_per_day2$steps)
median(steps_per_day2$steps)
```
The above value is slightly differs for median:
**Before**
Mean is 10766.19 and median is 10765

**After**
Mean is 10766.19 and median is 10766.19

We can observe that the median has changed and matched the mean.


## Are there differences in activity patterns between weekdays and weekends?

a. Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

```{R}
day <- weekdays(steps_data$date)
daylevel <- vector()
for (i in 1:nrow(steps_data)) {
    if (day[i] == "Saturday") {
       daylevel[i] <- "Weekend"
    } else if (day[i] == "Sunday") {
       daylevel[i] <- "Weekend"
    } else {
       daylevel[i] <- "Weekday"
    }
}
steps_data$daylevel <- daylevel
steps_data$daylevel <- factor(steps_data$daylevel)

stepsbyday <- aggregate(steps ~ interval + daylevel, data = steps_data, mean)
names(stepsbyday) <- c("interval", "daylevel", "steps")
```

b. Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data

```{R}
xyplot(steps ~ interval | daylevel, stepsbyday, type = "l", layout = c(1,2), xlab = "5-min Interval", ylab = "Number of Steps")
```

The activity patterns are different between weekend and weekdays as weekends has more peeks of over 100 number of steps compared to weekday. However, weekday has the greatest peak of over 200 number of steps.